create table tb_categoria (categoria_pai_id integer, id integer not null auto_increment, versao integer, nome varchar(100) not null, primary key (id)) engine=InnoDB;
create table tb_cliente (id integer not null auto_increment, versao integer, cpf varchar(14) not null, nome varchar(100) not null, primary key (id)) engine=InnoDB;
create table tb_cliente_contato (cliente_id integer not null, descricao varchar(255), tipo varchar(255) not null, primary key (cliente_id, tipo)) engine=InnoDB;
create table tb_cliente_detalhe (cliente_id integer not null, data_nascimento date, sexo enum ('FEMININO','MASCULINO') not null, primary key (cliente_id)) engine=InnoDB;
create table tb_estoque (id integer not null auto_increment, produto_id integer not null, quantidade integer, versao integer, primary key (id)) engine=InnoDB;
create table tb_item_pedido (pedido_id integer not null, preco_produto decimal(19,2) not null, produto_id integer not null, quantidade integer not null, versao integer, primary key (pedido_id, produto_id)) engine=InnoDB;
create table tb_nota_fiscal (pedido_id integer not null, versao integer, data_emissao datetime(6) not null, xml tinyblob not null, primary key (pedido_id)) engine=InnoDB;
create table tb_pagamento (pedido_id integer not null, versao integer, tipo_pagamento varchar(31) not null check ((tipo_pagamento in ('PagamentoBoleto','PagamentoCartao'))), numero_cartao varchar(50), codigo_barras varchar(100), status enum ('CANCELADO','PROCESSANDO','RECEBIDO') not null, primary key (pedido_id)) engine=InnoDB;
create table tb_pedido (cliente_id integer not null, estado varchar(2), id integer not null auto_increment, total decimal(19,2) not null, versao integer, data_conclusao datetime(6), data_criacao datetime(6) not null, data_ultima_atualizacao datetime(6), cep varchar(9), numero varchar(10), bairro varchar(50), cidade varchar(50), complemento varchar(50), logradouro varchar(100), status enum ('AGUARDANDO','CANCELADO','PAGO') not null, primary key (id)) engine=InnoDB;
create table tb_produto (id integer not null auto_increment, preco decimal(10,2), versao integer, data_criacao datetime(6) not null, data_ultima_atualizacao datetime(6), nome varchar(100) not null, descricao varchar(255), foto longblob, primary key (id)) engine=InnoDB;
create table tb_produto_atributo (produto_id integer not null, nome varchar(100) not null, valor varchar(255)) engine=InnoDB;
create table tb_produto_categoria (categoria_id integer not null, produto_id integer not null) engine=InnoDB;
create table tb_produto_tag (produto_id integer not null, tag varchar(50) not null) engine=InnoDB;
alter table tb_categoria add constraint unq_nome unique (nome);
create index idx_tb_cliente_nome on tb_cliente (nome);
alter table tb_cliente add constraint unq_tb_cliente_cpf unique (cpf);
alter table tb_estoque add constraint unq_produto_id unique (produto_id);
create index idx_tb_produto_nome on tb_produto (nome);
alter table tb_produto add constraint unq_tb_produto_nome unique (nome);
alter table tb_categoria add constraint fk_categoria_categoriapai foreign key (categoria_pai_id) references tb_categoria (id);
alter table tb_cliente_contato add constraint fk_cliente_contato_cliente foreign key (cliente_id) references tb_cliente (id);
alter table tb_cliente_detalhe add constraint fk_cliente_detalhe_cliente foreign key (cliente_id) references tb_cliente (id);
alter table tb_estoque add constraint fk_estoque_produto foreign key (produto_id) references tb_produto (id);
alter table tb_item_pedido add constraint fk_item_pedido_pedido foreign key (pedido_id) references tb_pedido (id);
alter table tb_item_pedido add constraint fk_item_pedido_produto foreign key (produto_id) references tb_produto (id);
alter table tb_nota_fiscal add constraint fk_nota_fiscal_pedido foreign key (pedido_id) references tb_pedido (id);
alter table tb_pagamento add constraint fk_pagamento_pedido foreign key (pedido_id) references tb_pedido (id);
alter table tb_pedido add constraint fk_pedido_cliente foreign key (cliente_id) references tb_cliente (id);
alter table tb_produto_atributo add constraint fk_produto_atributo_produto foreign key (produto_id) references tb_produto (id);
alter table tb_produto_categoria add constraint fk_produto_categoria_categoria foreign key (categoria_id) references tb_categoria (id);
alter table tb_produto_categoria add constraint fk_produto_categoria_produto foreign key (produto_id) references tb_produto (id);
alter table tb_produto_tag add constraint fk_produto_tag_produto foreign key (produto_id) references tb_produto (id);
